### ISSUE TITLE
context labels being positioned incorrectly

### ISSUE THREAD

**Issue by cmbirk** [JohnMcLear/ep_context#13]
They aren't lining up with their corresponding lines.  Probably due to font size differences (?)

**Comment by JohnMcLear** [comment]
Screen shot please :)

**Comment by cmbirk** [comment]
<img width="1153" alt="screen shot 2015-10-26 at 3 54 00 pm" src="https://cloud.githubusercontent.com/assets/764851/10740671/d48c9dae-7bf9-11e5-87e0-916747b16b38.png">

**Comment by JohnMcLear** [comment]
Can I see this live anywhere?  Looks like a bug.

**Comment by cmbirk** [comment]
Apologies, I just refreshed and now it's working... 😐Closing this unless it pops back up.
