### ISSUE TITLE
Add 'No Context' context label

### ISSUE THREAD

**Issue by cmbirk** [JohnMcLear/ep_context#15]
Not sold on the language of the label, but good enough for now.

We'll want to add some styling to set this apart as a warning as well.  Probably red, bold text

**Comment by JohnMcLear** [comment]
Only font-size & color will apply x-browser easily, color and weight are hit and miss..  I put a patch in for this anyway, feel free to change font size and just use color

**Comment by cmbirk** [comment]
For this I'm talking about the label off to the left side.  I want a visual warning that a line has no content so the drafter can go through and add context.

**Comment by JohnMcLear** [comment]
Oh shoot my bad...  Easy fix coming up

**Comment by JohnMcLear** [comment]
Done :)
