### ISSUE TITLE
New line focus issue

### ISSUE THREAD

**Issue by cmbirk** [JohnMcLear/ep_context#16]
Hitting:
1. Enter to create new line
2. Changing newline context

Loses focus on that line, so the user has to click back to start typing.  The line should hold caret focus.

**Comment by cmbirk** [comment]
I think this needs to be added on the select change function around line 60

**Comment by JohnMcLear** [comment]
This isn't happening for me, which browser are you experiencing this in?

**Comment by cmbirk** [comment]
Chrome 46.0.2490.80

**Comment by cmbirk** [comment]
This is actually happening any time I use the context selection.  I select a context and immediately go back to the keyboard -> the line is not in focus.  I think the solution is:
1.  Set a data attribute on the `#contextButtonsContainer` in the `reDrawControls` method.
2.  Grab that line number in the select change function around line 60
3.  After the select is changed and the context is applied, refocus on the given line number.

**Comment by JohnMcLear** [comment]
Ah I think I fixed this as part of another bug, give it a go :)
