### ISSUE TITLE
Copy and paste loses context and needs trimming

### ISSUE THREAD

**Issue by cmbirk** [JohnMcLear/ep_context#18]
Copying and pasting from this resolution into a whereas block

https://github.com/opengovfoundation/chicago-legislation-examples/blob/master/resolutions/pdf/R2015-232.pdf

causes this issue (screenshot)
<img width="1027" alt="screen shot 2015-10-27 at 12 47 29 pm" src="https://cloud.githubusercontent.com/assets/764851/10765551/aa94fb80-7ca9-11e5-8328-328e0a428a90.png">

**Comment by JohnMcLear** [comment]
I can't even select text from that PDF file, how are you doing that?

**Comment by JohnMcLear** [comment]
FWIW Copy/pasting from notepad etc. works fine on single line stuff

**Comment by cmbirk** [comment]
If you download the raw version, the browser pdf viewer will let you select the text.  I'll see if the same problem arises with a few Word docs.

**Comment by JohnMcLear** [comment]
That's an issue w/ the PDF, it has hard line breaks.  Copy/Paste it into notepad you will experience the same thing...

**Comment by JohnMcLear** [comment]
Can't replicate on Windows, could be Word on Mac issue

**Comment by JohnMcLear** [comment]
Was Etherpad out of date issue :)
