### ISSUE TITLE
Context lost

### ISSUE THREAD

**Issue by cmbirk** [JohnMcLear/ep_context#19]
Steps to reproduce:
1.  Create multiple whereas clauses
2.  Create multiple signature lines after
3.  Click into the last whereas clause and hit enter

The whereas clause that was clicked into and the new whereas clause lose context (screenshot)

<img width="1051" alt="screen shot 2015-10-27 at 12 57 53 pm" src="https://cloud.githubusercontent.com/assets/764851/10765711/746e8890-7caa-11e5-9f1e-f3d89a0f9210.png">

**Comment by JohnMcLear** [comment]
Unable to replicate -_-

**Comment by cmbirk** [comment]
Not getting this any more either, but am getting:
1.  Start from a blank document
2.  Type on line 1
3.  Set the context to `title`
4.  Hit enter and type.  Set context to `whereas`
5.  Hit enter and type.  Set context to `whereas`
6.  Click back into `title` line
7.  Hit enter to replicate
8.  Change context of replicated `title` line to `whereas`

This causes the current line to change to whereas, but changes the line below it to `title` for some reason

**Comment by JohnMcLear** [comment]
Issue is when you new line at end of pad if caret is on lastline

**Comment by JohnMcLear** [comment]
Fixed by removing double enter key removes context.
