### ISSUE TITLE
Need hotkeys for changing context

### ISSUE THREAD

**Issue by cmbirk** [JohnMcLear/ep_context#20]
I'm thinking Shift+Enter to open the selection, and then Shift+Tab to cycle through, and then Enter to select context.

**Comment by cmbirk** [comment]
@JohnMcLear does that make sense to you?

**Comment by JohnMcLear** [comment]
shift enter is used for line breaks in this plugin https://www.npmjs.com/package/ep_linebreak

**Comment by JohnMcLear** [comment]
Shift Tab already does unindent.  I will make it perform this task if select input isn't shown

**Comment by JohnMcLear** [comment]
basic buddy demo available in dynamic-last-line branch - getting a fair amount of cruft in this project now

**Comment by cmbirk** [comment]
I'm not completely tied to those keystrokes.  Is there a better few keystrokes that you would recommend?

**Comment by JohnMcLear** [comment]
If you are gonna use line breaks at any point I'd change if not you gtg

**Comment by cmbirk** [comment]
I can't think of a use case at the moment for that, but hate to make that assumption.  I'll rethink those.

**Comment by cmbirk** [comment]
Do you see any issues with shift+space?

Aside from the initiating keystroke, can we just use tab/arrow keys when the select is open to scroll through the contexts, and then enter to select?  

Right now it doesn't cycle back through when hitting the bottom as well.

That seems most intuitive to me.  Thoughts?

**Comment by JohnMcLear** [comment]
Yea cool will sort

**Comment by JohnMcLear** [comment]
Arrow keys is actually kinda bad, because if you want to move caret when select is open you can't, tab is prolly best.  Is that the behavior you want (where it blocks caret key location being moved) ?

**Comment by cmbirk** [comment]
Yeah, I think we want caret location being blocked when the select is open.  The use focus is on the select, so we don't want other things jumping around.

**Comment by JohnMcLear** [comment]
okies cool will use arrow keys then :)

**Comment by JohnMcLear** [comment]
Done, give that a go :)  Master branch btw

**Comment by cmbirk** [comment]
The `tab` button changes the focus outside of the selection.  It should either cycle the selection.

**Comment by JohnMcLear** [comment]
Caused by https://github.com/JohnMcLear/ep_context/blob/master/static/js/index.js#L279

**Comment by JohnMcLear** [comment]
Temporarily disable double enter logic

**Comment by JohnMcLear** [comment]
Done :)  Tab cycles context option
