### ISSUE TITLE
Indicator for each context

### ISSUE THREAD

**Issue by cmbirk** [JohnMcLear/ep_context#3]
It's very apparent what context the `whereas` lines are, but not context lines without pre-determined language.  We need some sort of indicator for the contexts, and I'm still thinking through what that should be.  Any thoughts @krues8dr?

**Comment by cmbirk** [comment]
@JohnMcLear is this something that revisiting the TOC discussion might help?  Right now I'm thinking of just floating a small indicator to the left of the page editor like the attached.  Obviously could use some styling, but things like titles, signatures, etc. wouldn't have template language attached and would be hard to understand at a glance.  cc @krues8dr
![indicators](https://cloud.githubusercontent.com/assets/764851/10670661/25ae6538-78ac-11e5-8121-d4055802dbb6.png)

**Comment by JohnMcLear** [comment]
/me shrugs, I'm not a UX guy ;)  I can do whatever you want though!  Don't mean to sound passive btw, just you "really" don't want my input on UI/UX stuff!

**Comment by krusynth** [comment]
I really wanna scrap the line numbers, which will tighten this up a lot.  I think as-is that looks good, but we will run into trouble when we get to nested contexts, which will happen before too long.  I still like the LIME way of doing things, where there's a box around each discrete element that has the name in it - that also will hint to users that each is an editable region unto itself.  Something like `padding: 15px; margin-bottom: 2rem; border: 1px solid #009; background-color: rgba(0,0,255,0.4);` or so.

**Comment by cmbirk** [comment]
I do think we need the line numbers so drafters have ways to reference content ( ie. "remove the whereas clause on line 6".  @JohnMcLear would you add the references on the left ( no nesting at this point, all references at the same level )?  I'll connect with Scout on this after we get that plugged in to get his thoughts.

I like the idea of having a more identifiable editing region, but the LIME experience throws a lot of people off.  Need to noodle on that one a bit more.

**Comment by JohnMcLear** [comment]
Done as MVP, needs a lot of optimization and UX polish..  VERY beta for now..

**Comment by cmbirk** [comment]
Yeah, I think it just needs some styling love.  I'll open an issue for that.
