### ISSUE TITLE
Add hotkey info text to floating controls

### ISSUE THREAD

**Issue by cmbirk** [JohnMcLear/ep_context#32]
just a small grey <shift_icon>+<spacebar icon>

(looking for the character codes now)

**Comment by cmbirk** [comment]
Well that was supposed to read (shift icon)+(spacebar icon)

**Comment by cmbirk** [comment]
Looks like:

shift icon: &#8679;
spacebar: &#9251;

**Comment by cmbirk** [comment]
Damn.  Codes are:

shift: `&#8679;`
spacebar: `&#9251;`

**Comment by cmbirk** [comment]
Small grey icons just above the floating controls

**Comment by JohnMcLear** [comment]
What do you mean by controls?  The + - thingy?

**Comment by JohnMcLear** [comment]
I pushed what I think you meant but pull and see if I was on the same page or not..

**Comment by cmbirk** [comment]
Thanks.  That's close, and I can take it from there.  Assigning to me.
