### ISSUE TITLE
Weird context switching on character delete

### ISSUE THREAD

**Issue by cmbirk** [JohnMcLear/ep_context#33]
Steps to recreate (from blank document):
1.  Create a couple `whereas` clauses
1.  Create a `resolved` clause
1.  Type up content in the `resolved` clause
1.  Hit backspace to remove the last character

After the last step, the `resolved` clause reverts to the previously set `whereas`

**Comment by JohnMcLear** [comment]
Git pull and see if this is resolved.  Backspace was doing some trippy stuff before, this should now be sorted.

**Comment by cmbirk** [comment]
Yep, this is working now :)
