### ISSUE TITLE
Can't change context bug

### ISSUE THREAD

**Issue by cmbirk** [JohnMcLear/ep_context#34]
I'm seeing this issue again when copying and pasting from [this document](https://github.com/opengovfoundation/chicago-legislation-examples/blob/master/resolutions/doc/example.doc): https://github.com/opengovfoundation/chicago-legislation-examples/blob/master/resolutions/doc/example.doc.

I just copy and paste the contents as a whole and go through removing any extra lines and setting the correct contexts.  When I get to the second `be it resolved` clause and attempt to set the signature line below, it won't let me change the last `be it resolved` to a signature.  I am seeing a response from `pad.js?callback=require.define:3321` that is a `COLLABROOM` object that contains an `ACCEPT_COMMIT` object.

There aren't any errors being logged to the console.

I am also seeing that the line above and the line that can't be changed both have a class of `ace-line` that the other lines don't have.  I've included a screenshot with the line in question selected in the HTML.

<img width="758" alt="screen shot 2015-11-02 at 2 12 06 pm" src="https://cloud.githubusercontent.com/assets/764851/10892955/ca5c93da-816b-11e5-9bda-aea179a6e3ae.png">

**Comment by JohnMcLear** [comment]
Tried to replicate but I can't...  I do however see when I change context on line 13 it breaks line 16..  http://10.0.0.12:9001/p/slkdjflksjdf2 is my local padId for my reference, I will work from that and try to resolve that bug and that should hopefully fix your issue too..

**Comment by JohnMcLear** [comment]
Pull and test :)

**Comment by cmbirk** [comment]
It looks like that fixed it.  What was the issue?

**Comment by JohnMcLear** [comment]
I think it was some cruft I left in from the big button initial implementation..  I can't seem to find anything that doesn't work after I removed the code...
