### ISSUE TITLE
Auto set context after paste event

### ISSUE THREAD

**Issue by cmbirk** [JohnMcLear/ep_context#35]
I'm just opening this to start thinking about how we could handle this.  I'm not sure how performant it would be to iterate each line and look for `Whereas` / `Be it resolved` / etc.

**Comment by JohnMcLear** [comment]
you wouldn't need to iterate each line, initially do an indexOf of the apool.atext value and if it matches then iterate :)

J

**Comment by cmbirk** [comment]
This is mainly working, except it doesn't update the labels on the left until the page is realoaded

**Comment by JohnMcLear** [comment]
Resolved
