### ISSUE TITLE
Another weird context switching

### ISSUE THREAD

**Issue by cmbirk** [JohnMcLear/ep_context#39]
Using the same [example doc](https://github.com/opengovfoundation/chicago-legislation-examples/blob/master/resolutions/doc/example.doc), here are the steps to recreate:
1.  Copy and paste into a blank pad
2.  Starting from the top, remove all blank lines

**As I remove the blank line after the last `whereas` clause, it sets the `resolved` clause below it as a `whereas` and unsets the context of the `whereas` clause above it.

I'm seeing this issue on our demo site.

**Comment by JohnMcLear** [comment]
Should also be fixed, give it a go :)

**Comment by cmbirk** [comment]
Well this is obviously fixed with the auto-removal of blank lines :)
