### ISSUE TITLE
First 'Be it resolved' clause not set until click

### ISSUE THREAD

**Issue by cmbirk** [JohnMcLear/ep_context#42]
If I copy our example word doc, the first 'Be It Resolved' clause originally appears as 'Be It Further Resolved'.  After clicking into the pad, it is correctly set as 'Be It Resolved'

**Comment by JohnMcLear** [comment]
Note to self this appears to be a race condition as I can re-create on the madison editor but not locally

**Comment by JohnMcLear** [comment]
Gah I can't replicate this now :(

**Comment by cmbirk** [comment]
You may reduce that timeout that I changed ( line 326 I believe ).

**Comment by JohnMcLear** [comment]
Timeout didn't make a difference in the end, got a fix in, please pull and test :)

**Comment by cmbirk** [comment]
I'm not seeing any new commits.  Did you push?

**Comment by JohnMcLear** [comment]
doh was rejected try now

**Comment by cmbirk** [comment]
This just swapped the issue.  Now both are 'Be it resolved' until clicked and then the 'Be It Further Resolved' is reconciled

**Comment by JohnMcLear** [comment]
Not getting the same thing locallyh

**Comment by JohnMcLear** [comment]
Getting that issue on your instance ;\

**Comment by JohnMcLear** [comment]
pushed a test fix,. give it a go plz :)

**Comment by cmbirk** [comment]
Just pulled, and still seeing the issue

**Comment by JohnMcLear** [comment]
ughh ;\

**Comment by JohnMcLear** [comment]
okay leave it with me I can replicate locally now

**Comment by JohnMcLear** [comment]
plz pull and test

**Comment by cmbirk** [comment]
That appears to have done the trick :)
