### ISSUE TITLE
Strip content from end of line

### ISSUE THREAD

**Issue by cmbirk** [JohnMcLear/ep_context#45]
Just like we do with `whereas` and `be it resolved`, the clerk's team said it would be useful to strip that content at the end of the line.  Sometimes the end of a line is "therefore;" instead of "now, therefore;", which starts to get messy if you're trying to account for every use case.  I think if we stick with stripping whatever content we're auto-adding that would be fine.

**Comment by JohnMcLear** [comment]
Last match `/s/"therefor"/""` ? -- This might be dangerous actually, I will need to make sure strpos is strlength - replacementlength

and `and;`

**Comment by cmbirk** [comment]
`/s/"now, therefore;"` for now.  The `/s/"therefore"` match would be a fuzzy match of the template language that I don't think we want to dive into just yet

**Comment by JohnMcLear** [comment]
Done
