### ISSUE TITLE
Strip styling

### ISSUE THREAD

**Issue by cmbirk** [JohnMcLear/ep_context#46]
Using an example doc here at the clerk's office to walk them through it, the copy+paste process kept some of the styling on the `no context` lines.  This was confusing and they felt they needed to reconcile that.  I think this is a good example of setting a zero(or minimal)-styling expectation and focus on the content.  

Can we strip any styling on copy+paste?

**Comment by JohnMcLear** [comment]
We could remove `all` style formatting (bold/underline/italic) on document paste

**Comment by JohnMcLear** [comment]
I did this by hiding bold / underline

**Comment by cmbirk** [comment]
Does it make more sense to try and strip the styling tags on copy+paste vs. changing the default styling?

**Comment by JohnMcLear** [comment]
I tried that first and it was tricky to do.  I can have another go if you want :)
----- Reply message -----
