### ISSUE TITLE
Force Page View

### ISSUE THREAD

**Issue by cmbirk** [JohnMcLear/ep_context#5]
I had to select this as a setting.  If this plugin is active we'll need to force that setting.

**Comment by JohnMcLear** [comment]
This should actually be set in settings.json, see https://github.com/ether/ep_page_view

I could make it force it but some people wouldn't want that..  Perhaps if page view isn't available the select on top bar should only be available and not the side options?

**Comment by cmbirk** [comment]
We're not really working with a mind toward the top options at the moment.  For now, I can set it in our settings.json file, but may want to revisit.
