### ISSUE TITLE
Finish adding context blocks

### ISSUE THREAD

**Issue by cmbirk** [JohnMcLear/ep_context#9]
Finish adding context block references in other areas of the plugin ( eg. shared.js )

**Comment by JohnMcLear** [comment]
Found where they didn't go...  https://github.com/JohnMcLear/ep_context/blob/resolution-big-button/index.js#L93

They need to be in there too :)

**Comment by cmbirk** [comment]
Thanks.  I'll add them there.  Thoughts on the best place to keep one array?

**Comment by cmbirk** [comment]
This was finished in 23178bb
